services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agenda_frontend
    ports:
      - "7000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3000
    volumes:
      - ./:/app:delegated
      - frontend_node_modules:/app/node_modules
      - frontend_next:/app/.next
    restart: unless-stopped
    networks:
      - agenda-net

networks:
  agenda-net:
    external: true

volumes:
  frontend_node_modules:
    driver: local
  frontend_next:
    driver: local