services:
  postgres:
    image: postgres:16
    container_name: test_agendadb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "7010:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - agenda-net

networks:
  agenda-net:
    external: true

volumes:
  postgres_data:
    driver: local