version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: test_agendadb
    environment:
      POSTGRES_USER: useradmin
      POSTGRES_PASSWORD: snHmPrrxqBZFeguMPAMRRmKBujunuKVt
      POSTGRES_DB: agenda_db
    ports:
      - "7010:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - agenda-net

networks:
  agenda-net:
    external: true

volumes:
  postgres_data:
    driver: local

#database_url: postgresql://useradmin:snHmPrrxqBZFeguMPAMRRmKBujunuKVt@test_agendadb:5432/agenda_db